/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const adminCategoryService: typeof import('@/plugins/api/services').adminCategoryService
  const adminOrderService: typeof import('@/plugins/api/services').adminOrderService
  const adminProductService: typeof import('@/plugins/api/services').adminProductService
  const adminPromotionService: typeof import('@/plugins/api/services').adminPromotionService
  const adminReviewService: typeof import('@/plugins/api/services').adminReviewService
  const adminUserService: typeof import('@/plugins/api/services').adminUserService
  const auditActionClasses: typeof import('./helpers/statusHelpers').auditActionClasses
  const auditActionKeys: typeof import('./helpers/statusHelpers').auditActionKeys
  const auditActionLabels: typeof import('./helpers/statusHelpers').auditActionLabels
  const authService: typeof import('@/plugins/api/services').authService
  const camelToSnake: typeof import('./utils/string').camelToSnake
  const capitalize: typeof import('./utils/string').capitalize
  const cartService: typeof import('@/plugins/api/services').cartService
  const categoryService: typeof import('@/plugins/api/services').categoryService
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const formatDate: typeof import('./utils/format').formatDate
  const formatDateTime: typeof import('./utils/format').formatDateTime
  const formatNumber: typeof import('./utils/format').formatNumber
  const formatPrice: typeof import('./utils/format').formatPrice
  const formatRelativeTime: typeof import('./utils/format').formatRelativeTime
  const generateSlug: typeof import('./utils/string').generateSlug
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getEcho: typeof import('./modules/admin/chat/composables/useRealtime').getEcho
  const getOrderStatusClass: typeof import('./helpers/statusHelpers').getOrderStatusClass
  const getOrderStatusLabel: typeof import('./helpers/statusHelpers').getOrderStatusLabel
  const getReturnStatusClass: typeof import('./helpers/statusHelpers').getReturnStatusClass
  const getReturnStatusLabel: typeof import('./helpers/statusHelpers').getReturnStatusLabel
  const h: typeof import('vue').h
  const initConsoleSanitizer: typeof import('./helpers/consoleSanitizer').initConsoleSanitizer
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isValidEmail: typeof import('./utils/string').isValidEmail
  const isValidPhone: typeof import('./utils/string').isValidPhone
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const membershipService: typeof import('@/plugins/api/services').membershipService
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const orderService: typeof import('@/plugins/api/services').orderService
  const orderStatusClasses: typeof import('./helpers/statusHelpers').orderStatusClasses
  const orderStatusKeys: typeof import('./helpers/statusHelpers').orderStatusKeys
  const orderStatusLabels: typeof import('./helpers/statusHelpers').orderStatusLabels
  const pointTransactionClasses: typeof import('./helpers/statusHelpers').pointTransactionClasses
  const pointTransactionKeys: typeof import('./helpers/statusHelpers').pointTransactionKeys
  const pointTransactionLabels: typeof import('./helpers/statusHelpers').pointTransactionLabels
  const productService: typeof import('@/plugins/api/services').productService
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const reportService: typeof import('@/plugins/api/services').reportService
  const resolveComponent: typeof import('vue').resolveComponent
  const returnService: typeof import('@/plugins/api/services').returnService
  const returnStatusClasses: typeof import('./helpers/statusHelpers').returnStatusClasses
  const returnStatusKeys: typeof import('./helpers/statusHelpers').returnStatusKeys
  const returnStatusLabels: typeof import('./helpers/statusHelpers').returnStatusLabels
  const sanitizeHtml: typeof import('./utils/sanitize').sanitizeHtml
  const sanitizeSimpleHtml: typeof import('./utils/sanitize').sanitizeSimpleHtml
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const settingsService: typeof import('@/plugins/api/services').settingsService
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const snakeToCamel: typeof import('./utils/string').snakeToCamel
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const truncate: typeof import('./utils/string').truncate
  const unref: typeof import('vue').unref
  const useAdminCategories: typeof import('./modules/admin/products/composables/useAdminCategories').useAdminCategories
  const useAdminCategoryStore: typeof import('./modules/admin/categories/store/store').useAdminCategoryStore
  const useAdminList: typeof import('./composables/useAdminList').useAdminList
  const useAdminOrderStore: typeof import('./modules/admin/orders/store/store').useAdminOrderStore
  const useAdminOrders: typeof import('./modules/admin/orders/composables/useAdminOrders').useAdminOrders
  const useAdminProductStore: typeof import('./modules/admin/products/store/store').useAdminProductStore
  const useAdminProducts: typeof import('./modules/admin/products/composables/useAdminProducts').useAdminProducts
  const useAdminPromotionStore: typeof import('./modules/admin/promotions/store/store').useAdminPromotionStore
  const useAdminPromotions: typeof import('./modules/admin/promotions/composables/useAdminPromotions').useAdminPromotions
  const useArticleStore: typeof import('./modules/landing/articles/store/store').useArticleStore
  const useArticles: typeof import('./modules/landing/articles/composables/useArticles').useArticles
  const useAttrs: typeof import('vue').useAttrs
  const useAuditActionLabel: typeof import('./helpers/statusHelpers').useAuditActionLabel
  const useAuditLogs: typeof import('./modules/admin/erp/audit-logs/composables/useAuditLogs').useAuditLogs
  const useAuth: typeof import('./modules/landing/auth/composables/useAuth').useAuth
  const useAuthStore: typeof import('@/stores').useAuthStore
  const useAutoConnect: typeof import('./modules/admin/chat/composables/useRealtime').useAutoConnect
  const useAutoTranslate: typeof import('./composables/useAutoTranslate').default
  const useAutomations: typeof import('./modules/admin/erp/automations/composables/useAutomations').useAutomations
  const useCart: typeof import('./modules/landing/cart/composables/useCart').useCart
  const useCartStore: typeof import('./modules/landing/cart/store/store').useCartStore
  const useCheckout: typeof import('./modules/landing/orders/composables/useCheckout').useCheckout
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCustomers: typeof import('./modules/admin/erp/customers/composables/useCustomers').useCustomers
  const useExpenseCategories: typeof import('./modules/admin/erp/expenses/composables/useExpenseCategories').useExpenseCategories
  const useExpenses: typeof import('./modules/admin/erp/expenses/composables/useExpenses').useExpenses
  const useGlobalPolling: typeof import('./modules/admin/chat/composables/useRealtime').useGlobalPolling
  const useHome: typeof import('./modules/landing/home/composables/useHome').useHome
  const useHomeStore: typeof import('./modules/landing/home/store/store').useHomeStore
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLandingCategories: typeof import('./modules/landing/categories/composables/useLandingCategories').useLandingCategories
  const useLandingCategoryStore: typeof import('./modules/landing/categories/store/store').useLandingCategoryStore
  const useLandingOrderStore: typeof import('./modules/landing/orders/store/store').useLandingOrderStore
  const useLandingOrders: typeof import('./modules/landing/orders/composables/useLandingOrders').useLandingOrders
  const useLandingProductStore: typeof import('./modules/landing/products/store/store').useLandingProductStore
  const useLandingProducts: typeof import('./modules/landing/products/composables/useLandingProducts').useLandingProducts
  const useLandingPromotionStore: typeof import('./modules/landing/promotions/store/store').useLandingPromotionStore
  const useLandingPromotions: typeof import('./modules/landing/promotions/composables/useLandingPromotions').useLandingPromotions
  const useLink: typeof import('vue-router').useLink
  const useLoyalty: typeof import('./modules/landing/loyalty/composables/useLoyalty').useLoyalty
  const useLoyaltyStore: typeof import('./modules/landing/loyalty/store/store').useLoyaltyStore
  const useMembership: typeof import('./modules/admin/erp/membership/composables/useMembership').useMembership
  const useModel: typeof import('vue').useModel
  const useOrderStatusLabel: typeof import('./helpers/statusHelpers').useOrderStatusLabel
  const usePagination: typeof import('./composables/usePagination').usePagination
  const usePermission: typeof import('./composables/usePermission').usePermission
  const usePermissions: typeof import('./modules/admin/erp/permissions/composables/usePermissions').usePermissions
  const usePointTransactionLabel: typeof import('./helpers/statusHelpers').usePointTransactionLabel
  const usePoints: typeof import('./modules/admin/erp/points/composables/usePoints').usePoints
  const useProductModal: typeof import('./modules/admin/warehouses/composables/useProductModal').useProductModal
  const useProfile: typeof import('./modules/landing/profile/composables/useProfile').useProfile
  const useRealtime: typeof import('./modules/admin/chat/composables/useRealtime').useRealtime
  const useReturnStatusLabel: typeof import('./helpers/statusHelpers').useReturnStatusLabel
  const useReturns: typeof import('./modules/admin/erp/returns/composables/useReturns').useReturns
  const useReviewStore: typeof import('./modules/admin/reviews/store/store').useReviewStore
  const useReviews: typeof import('./modules/admin/reviews/composables/useReviews').useReviews
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSwal: typeof import('./utils/useSwal').useSwal
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUserStatusLabel: typeof import('./helpers/statusHelpers').useUserStatusLabel
  const useUserStore: typeof import('./modules/admin/users/store/store').useUserStore
  const useUsers: typeof import('./modules/admin/users/composables/useUsers').useUsers
  const useVoiceRecorder: typeof import('./modules/admin/chat/composables/useVoiceRecorder').useVoiceRecorder
  const useWarehouseProducts: typeof import('./modules/admin/warehouses/composables/useWarehouseProducts').useWarehouseProducts
  const useWarehouseStore: typeof import('./modules/admin/warehouses/store/store').useWarehouseStore
  const useWishlist: typeof import('./modules/landing/wishlist/composables/useWishlist').useWishlist
  const useWishlistStore: typeof import('./modules/landing/wishlist/store/store').useWishlistStore
  const userStatusClasses: typeof import('./helpers/statusHelpers').userStatusClasses
  const userStatusKeys: typeof import('./helpers/statusHelpers').userStatusKeys
  const userStatusLabels: typeof import('./helpers/statusHelpers').userStatusLabels
  const warehouseService: typeof import('@/plugins/api/services').warehouseService
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { UseAdminListOptions } from './composables/useAdminList'
  import('./composables/useAdminList')
  // @ts-ignore
  export type { TranslatableField } from './composables/useAutoTranslate'
  import('./composables/useAutoTranslate')
  // @ts-ignore
  export type { UsePaginationOptions } from './composables/usePagination'
  import('./composables/usePagination')
  // @ts-ignore
  export type { SwalOptions } from './utils/useSwal'
  import('./utils/useSwal')
  // @ts-ignore
  export type { VoiceRecorderState } from './modules/admin/chat/composables/useVoiceRecorder'
  import('./modules/admin/chat/composables/useVoiceRecorder')
  // @ts-ignore
  export type { CartItem, Cart } from './modules/landing/cart/composables/useCart'
  import('./modules/landing/cart/composables/useCart')
  // @ts-ignore
  export type { ShippingAddress, CheckoutForm, PaymentMethod } from './modules/landing/orders/composables/useCheckout'
  import('./modules/landing/orders/composables/useCheckout')
  // @ts-ignore
  export type { OrderItem, Order, Shipper } from './modules/admin/orders/store/store'
  import('./modules/admin/orders/store/store')
  // @ts-ignore
  export type { UserForm } from './modules/admin/users/store/store'
  import('./modules/admin/users/store/store')
  // @ts-ignore
  export type { WarehouseProduct, ProductForm, StockForm } from './modules/admin/warehouses/store/store'
  import('./modules/admin/warehouses/store/store')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly adminCategoryService: UnwrapRef<typeof import('@/plugins/api/services')['adminCategoryService']>
    readonly adminOrderService: UnwrapRef<typeof import('@/plugins/api/services')['adminOrderService']>
    readonly adminProductService: UnwrapRef<typeof import('@/plugins/api/services')['adminProductService']>
    readonly adminPromotionService: UnwrapRef<typeof import('@/plugins/api/services')['adminPromotionService']>
    readonly adminReviewService: UnwrapRef<typeof import('@/plugins/api/services')['adminReviewService']>
    readonly adminUserService: UnwrapRef<typeof import('@/plugins/api/services')['adminUserService']>
    readonly auditActionClasses: UnwrapRef<typeof import('./helpers/statusHelpers')['auditActionClasses']>
    readonly auditActionKeys: UnwrapRef<typeof import('./helpers/statusHelpers')['auditActionKeys']>
    readonly auditActionLabels: UnwrapRef<typeof import('./helpers/statusHelpers')['auditActionLabels']>
    readonly authService: UnwrapRef<typeof import('@/plugins/api/services')['authService']>
    readonly camelToSnake: UnwrapRef<typeof import('./utils/string')['camelToSnake']>
    readonly capitalize: UnwrapRef<typeof import('./utils/string')['capitalize']>
    readonly cartService: UnwrapRef<typeof import('@/plugins/api/services')['cartService']>
    readonly categoryService: UnwrapRef<typeof import('@/plugins/api/services')['categoryService']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatDate: UnwrapRef<typeof import('./utils/format')['formatDate']>
    readonly formatDateTime: UnwrapRef<typeof import('./utils/format')['formatDateTime']>
    readonly formatNumber: UnwrapRef<typeof import('./utils/format')['formatNumber']>
    readonly formatPrice: UnwrapRef<typeof import('./utils/format')['formatPrice']>
    readonly formatRelativeTime: UnwrapRef<typeof import('./utils/format')['formatRelativeTime']>
    readonly generateSlug: UnwrapRef<typeof import('./utils/string')['generateSlug']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getEcho: UnwrapRef<typeof import('./modules/admin/chat/composables/useRealtime')['getEcho']>
    readonly getOrderStatusClass: UnwrapRef<typeof import('./helpers/statusHelpers')['getOrderStatusClass']>
    readonly getOrderStatusLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['getOrderStatusLabel']>
    readonly getReturnStatusClass: UnwrapRef<typeof import('./helpers/statusHelpers')['getReturnStatusClass']>
    readonly getReturnStatusLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['getReturnStatusLabel']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly initConsoleSanitizer: UnwrapRef<typeof import('./helpers/consoleSanitizer')['initConsoleSanitizer']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isValidEmail: UnwrapRef<typeof import('./utils/string')['isValidEmail']>
    readonly isValidPhone: UnwrapRef<typeof import('./utils/string')['isValidPhone']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly membershipService: UnwrapRef<typeof import('@/plugins/api/services')['membershipService']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly orderService: UnwrapRef<typeof import('@/plugins/api/services')['orderService']>
    readonly orderStatusClasses: UnwrapRef<typeof import('./helpers/statusHelpers')['orderStatusClasses']>
    readonly orderStatusKeys: UnwrapRef<typeof import('./helpers/statusHelpers')['orderStatusKeys']>
    readonly orderStatusLabels: UnwrapRef<typeof import('./helpers/statusHelpers')['orderStatusLabels']>
    readonly pointTransactionClasses: UnwrapRef<typeof import('./helpers/statusHelpers')['pointTransactionClasses']>
    readonly pointTransactionKeys: UnwrapRef<typeof import('./helpers/statusHelpers')['pointTransactionKeys']>
    readonly pointTransactionLabels: UnwrapRef<typeof import('./helpers/statusHelpers')['pointTransactionLabels']>
    readonly productService: UnwrapRef<typeof import('@/plugins/api/services')['productService']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly reportService: UnwrapRef<typeof import('@/plugins/api/services')['reportService']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly returnService: UnwrapRef<typeof import('@/plugins/api/services')['returnService']>
    readonly returnStatusClasses: UnwrapRef<typeof import('./helpers/statusHelpers')['returnStatusClasses']>
    readonly returnStatusKeys: UnwrapRef<typeof import('./helpers/statusHelpers')['returnStatusKeys']>
    readonly returnStatusLabels: UnwrapRef<typeof import('./helpers/statusHelpers')['returnStatusLabels']>
    readonly sanitizeHtml: UnwrapRef<typeof import('./utils/sanitize')['sanitizeHtml']>
    readonly sanitizeSimpleHtml: UnwrapRef<typeof import('./utils/sanitize')['sanitizeSimpleHtml']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly settingsService: UnwrapRef<typeof import('@/plugins/api/services')['settingsService']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly snakeToCamel: UnwrapRef<typeof import('./utils/string')['snakeToCamel']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly truncate: UnwrapRef<typeof import('./utils/string')['truncate']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAdminCategories: UnwrapRef<typeof import('./modules/admin/products/composables/useAdminCategories')['useAdminCategories']>
    readonly useAdminList: UnwrapRef<typeof import('./composables/useAdminList')['useAdminList']>
    readonly useAdminOrderStore: UnwrapRef<typeof import('./modules/admin/orders/store/store')['useAdminOrderStore']>
    readonly useAdminOrders: UnwrapRef<typeof import('./modules/admin/orders/composables/useAdminOrders')['useAdminOrders']>
    readonly useAdminProductStore: UnwrapRef<typeof import('./modules/admin/products/store/store')['useAdminProductStore']>
    readonly useAdminProducts: UnwrapRef<typeof import('./modules/admin/products/composables/useAdminProducts')['useAdminProducts']>
    readonly useAdminPromotionStore: UnwrapRef<typeof import('./modules/admin/promotions/store/store')['useAdminPromotionStore']>
    readonly useAdminPromotions: UnwrapRef<typeof import('./modules/admin/promotions/composables/useAdminPromotions')['useAdminPromotions']>
    readonly useArticleStore: UnwrapRef<typeof import('./modules/landing/articles/store/store')['useArticleStore']>
    readonly useArticles: UnwrapRef<typeof import('./modules/landing/articles/composables/useArticles')['useArticles']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuditActionLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['useAuditActionLabel']>
    readonly useAuditLogs: UnwrapRef<typeof import('./modules/admin/erp/audit-logs/composables/useAuditLogs')['useAuditLogs']>
    readonly useAuth: UnwrapRef<typeof import('./modules/landing/auth/composables/useAuth')['useAuth']>
    readonly useAuthStore: UnwrapRef<typeof import('@/stores')['useAuthStore']>
    readonly useAutoConnect: UnwrapRef<typeof import('./modules/admin/chat/composables/useRealtime')['useAutoConnect']>
    readonly useAutoTranslate: UnwrapRef<typeof import('./composables/useAutoTranslate')['default']>
    readonly useAutomations: UnwrapRef<typeof import('./modules/admin/erp/automations/composables/useAutomations')['useAutomations']>
    readonly useCart: UnwrapRef<typeof import('./modules/landing/cart/composables/useCart')['useCart']>
    readonly useCartStore: UnwrapRef<typeof import('./modules/landing/cart/store/store')['useCartStore']>
    readonly useCheckout: UnwrapRef<typeof import('./modules/landing/orders/composables/useCheckout')['useCheckout']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCustomers: UnwrapRef<typeof import('./modules/admin/erp/customers/composables/useCustomers')['useCustomers']>
    readonly useExpenseCategories: UnwrapRef<typeof import('./modules/admin/erp/expenses/composables/useExpenseCategories')['useExpenseCategories']>
    readonly useExpenses: UnwrapRef<typeof import('./modules/admin/erp/expenses/composables/useExpenses')['useExpenses']>
    readonly useGlobalPolling: UnwrapRef<typeof import('./modules/admin/chat/composables/useRealtime')['useGlobalPolling']>
    readonly useHome: UnwrapRef<typeof import('./modules/landing/home/composables/useHome')['useHome']>
    readonly useHomeStore: UnwrapRef<typeof import('./modules/landing/home/store/store')['useHomeStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLandingCategories: UnwrapRef<typeof import('./modules/landing/categories/composables/useLandingCategories')['useLandingCategories']>
    readonly useLandingCategoryStore: UnwrapRef<typeof import('./modules/landing/categories/store/store')['useLandingCategoryStore']>
    readonly useLandingOrderStore: UnwrapRef<typeof import('./modules/landing/orders/store/store')['useLandingOrderStore']>
    readonly useLandingOrders: UnwrapRef<typeof import('./modules/landing/orders/composables/useLandingOrders')['useLandingOrders']>
    readonly useLandingProductStore: UnwrapRef<typeof import('./modules/landing/products/store/store')['useLandingProductStore']>
    readonly useLandingProducts: UnwrapRef<typeof import('./modules/landing/products/composables/useLandingProducts')['useLandingProducts']>
    readonly useLandingPromotionStore: UnwrapRef<typeof import('./modules/landing/promotions/store/store')['useLandingPromotionStore']>
    readonly useLandingPromotions: UnwrapRef<typeof import('./modules/landing/promotions/composables/useLandingPromotions')['useLandingPromotions']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLoyalty: UnwrapRef<typeof import('./modules/landing/loyalty/composables/useLoyalty')['useLoyalty']>
    readonly useLoyaltyStore: UnwrapRef<typeof import('./modules/landing/loyalty/store/store')['useLoyaltyStore']>
    readonly useMembership: UnwrapRef<typeof import('./modules/admin/erp/membership/composables/useMembership')['useMembership']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useOrderStatusLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['useOrderStatusLabel']>
    readonly usePagination: UnwrapRef<typeof import('./composables/usePagination')['usePagination']>
    readonly usePermission: UnwrapRef<typeof import('./composables/usePermission')['usePermission']>
    readonly usePermissions: UnwrapRef<typeof import('./modules/admin/erp/permissions/composables/usePermissions')['usePermissions']>
    readonly usePointTransactionLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['usePointTransactionLabel']>
    readonly usePoints: UnwrapRef<typeof import('./modules/admin/erp/points/composables/usePoints')['usePoints']>
    readonly useProductModal: UnwrapRef<typeof import('./modules/admin/warehouses/composables/useProductModal')['useProductModal']>
    readonly useProfile: UnwrapRef<typeof import('./modules/landing/profile/composables/useProfile')['useProfile']>
    readonly useRealtime: UnwrapRef<typeof import('./modules/admin/chat/composables/useRealtime')['useRealtime']>
    readonly useReturnStatusLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['useReturnStatusLabel']>
    readonly useReturns: UnwrapRef<typeof import('./modules/admin/erp/returns/composables/useReturns')['useReturns']>
    readonly useReviewStore: UnwrapRef<typeof import('./modules/admin/reviews/store/store')['useReviewStore']>
    readonly useReviews: UnwrapRef<typeof import('./modules/admin/reviews/composables/useReviews')['useReviews']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSwal: UnwrapRef<typeof import('./utils/useSwal')['useSwal']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useUserStatusLabel: UnwrapRef<typeof import('./helpers/statusHelpers')['useUserStatusLabel']>
    readonly useUserStore: UnwrapRef<typeof import('./modules/admin/users/store/store')['useUserStore']>
    readonly useUsers: UnwrapRef<typeof import('./modules/admin/users/composables/useUsers')['useUsers']>
    readonly useVoiceRecorder: UnwrapRef<typeof import('./modules/admin/chat/composables/useVoiceRecorder')['useVoiceRecorder']>
    readonly useWarehouseProducts: UnwrapRef<typeof import('./modules/admin/warehouses/composables/useWarehouseProducts')['useWarehouseProducts']>
    readonly useWarehouseStore: UnwrapRef<typeof import('./modules/admin/warehouses/store/store')['useWarehouseStore']>
    readonly useWishlist: UnwrapRef<typeof import('./modules/landing/wishlist/composables/useWishlist')['useWishlist']>
    readonly useWishlistStore: UnwrapRef<typeof import('./modules/landing/wishlist/store/store')['useWishlistStore']>
    readonly userStatusClasses: UnwrapRef<typeof import('./helpers/statusHelpers')['userStatusClasses']>
    readonly userStatusKeys: UnwrapRef<typeof import('./helpers/statusHelpers')['userStatusKeys']>
    readonly userStatusLabels: UnwrapRef<typeof import('./helpers/statusHelpers')['userStatusLabels']>
    readonly warehouseService: UnwrapRef<typeof import('@/plugins/api/services')['warehouseService']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}