/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPageHeader: typeof import('./modules/admin/components/AdminPageHeader.vue')['default']
    AdminSearch: typeof import('./modules/admin/components/AdminSearch.vue')['default']
    AdminTable: typeof import('./modules/admin/components/AdminTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseIcon: typeof import('./components/UI/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/UI/BaseInput.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    DAction: typeof import('./components/data/DAction.vue')['default']
    DButton: typeof import('./components/UI/DButton.vue')['default']
    DCard: typeof import('./components/UI/DCard.vue')['default']
    DEmptyState: typeof import('./components/data/DEmptyState.vue')['default']
    DLoading: typeof import('./components/data/DLoading.vue')['default']
    DModal: typeof import('./components/data/DModal.vue')['default']
    DSelect: typeof import('./components/UI/DSelect.vue')['default']
    DTable: typeof import('./components/data/DTable.vue')['default']
    DTextarea: typeof import('./components/UI/DTextarea.vue')['default']
    EmptyState: typeof import('./modules/landing/components/EmptyState.vue')['default']
    ImageHoverPreview: typeof import('./modules/landing/components/ImageHoverPreview.vue')['default']
    ImageModal: typeof import('./components/ImageModal.vue')['default']
    LandingFooter: typeof import('./components/layouts/LandingFooter.vue')['default']
    LandingHeader: typeof import('./components/layouts/LandingHeader.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LoadingState: typeof import('./modules/landing/components/LoadingState.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    NotificationBell: typeof import('./modules/admin/components/NotificationBell.vue')['default']
    Pagination: typeof import('./modules/admin/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./modules/landing/components/SectionHeader.vue')['default']
    SliderNavigation: typeof import('./modules/landing/components/SliderNavigation.vue')['default']
    StarRating: typeof import('./modules/landing/components/StarRating.vue')['default']
    StatusBadge: typeof import('./modules/admin/components/StatusBadge.vue')['default']
  }
}
