/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPageHeader: typeof import('./shared/components/admin/AdminPageHeader.vue')['default']
    AdminSearch: typeof import('./shared/components/admin/AdminSearch.vue')['default']
    AdminTable: typeof import('./shared/components/admin/AdminTable.vue')['default']
    AppFooter: typeof import('./shared/components/AppFooter.vue')['default']
    AppHeader: typeof import('./shared/components/AppHeader.vue')['default']
    BaseInput: typeof import('./components/UI/BaseInput.vue')['default']
    BaseModal: typeof import('./shared/components/BaseModal.vue')['default']
    DAction: typeof import('./components/data/DAction.vue')['default']
    DButton: typeof import('./components/UI/DButton.vue')['default']
    DCard: typeof import('./components/UI/DCard.vue')['default']
    DEmptyState: typeof import('./components/data/DEmptyState.vue')['default']
    DLoading: typeof import('./components/data/DLoading.vue')['default']
    DModal: typeof import('./components/data/DModal.vue')['default']
    DSelect: typeof import('./components/UI/DSelect.vue')['default']
    DTable: typeof import('./components/data/DTable.vue')['default']
    DTextarea: typeof import('./components/UI/DTextarea.vue')['default']
    LandingFooter: typeof import('./components/layouts/LandingFooter.vue')['default']
    LandingHeader: typeof import('./components/layouts/LandingHeader.vue')['default']
    LanguageSwitcher: typeof import('./shared/components/LanguageSwitcher.vue')['default']
    NotFound: typeof import('./shared/components/NotFound.vue')['default']
    Pagination: typeof import('./shared/components/admin/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./shared/components/admin/StatusBadge.vue')['default']
  }
}
